services:
  semaphore-db:
    image: postgres:15-alpine
    container_name: semaphore-db
    environment:
      POSTGRES_USER: ${SEMAPHORE_DB_USER:-semaphore}
      POSTGRES_PASSWORD: ${SEMAPHORE_DB_PASS}
      POSTGRES_DB: ${SEMAPHORE_DB_NAME:-semaphore}
    volumes:
      - /opt/containerd/semaphore/db:/var/lib/postgresql/data
    restart: unless-stopped

  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    ports:
      - "13000:3000"
    environment:
      SEMAPHORE_DB_USER: ${SEMAPHORE_DB_USER:-semaphore}
      SEMAPHORE_DB_PASS: ${SEMAPHORE_DB_PASS}
      SEMAPHORE_DB_HOST: semaphore-db
      SEMAPHORE_DB_PORT: "5432"
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: ${SEMAPHORE_DB_NAME:-semaphore}
      SEMAPHORE_PLAYBOOK_PATH: /home/semaphore/playbooks
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASS}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME:-Admin}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL:-admin@example.com}
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN_USER:-admin}
    depends_on:
      - semaphore-db
    volumes:
      - /opt/containerd/semaphore/playbooks:/home/semaphore/playbooks
    restart: unless-stopped
