services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
